apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: shipwright-trigger
spec:
  params:
    - name: BUILD_NAME
      type: string
      description: The name of the Shipwright Build to run
    - name: NAMESPACE
      type: string
      description: The namespace where the BuildRun should be created
  steps:
    - name: trigger
      image: bitnami/kubectl:latest
      script: |
        #!/bin/sh
        set -e
        echo "🔄 Triggering Shipwright BuildRun for $(params.BUILD_NAME) in namespace $(params.NAMESPACE)"
        cat <<EOF | kubectl create -f -
        apiVersion: shipwright.io/v1alpha1
        kind: BuildRun
        metadata:
          generateName: $(params.BUILD_NAME)-
          namespace: $(params.NAMESPACE)
        spec:
          buildRef:
            name: $(params.BUILD_NAME)
        EOF

