apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: java-webapp-run
spec:
  pipelineRef:
    name: java-webapp-pipeline
  params:
    - name: git-url
      value: https://github.com/YOUR_ORG/devops-workshop.git
    - name: git-revision
      value: main
    - name: build-name
      value: java-webapp
    - name: namespace
      value: student01
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: shared-pvc
