apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-webapp-pipeline
spec:
  params:
    - name: git-url
      type: string
      description: Public Git repo URL
    - name: git-revision
      type: string
      description: Branch, tag or commit
      default: "dev"
    - name: build-name
      type: string
      description: Shipwright Build name
    - name: namespace
      type: string
      description: Target OpenShift project
  workspaces:
    - name: source
      description: Where source is checked out
  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: Task
        apiVersion: tekton.dev/v1
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: source

    - name: build
      runAfter: [clone]
      taskRef:
        name: maven-build
        kind: Task
        apiVersion: tekton.dev/v1
      workspaces:
        - name: source
          workspace: source

    - name: sanity
      runAfter: [build]
      taskRef:
        name: war-sanity-check
        kind: Task
        apiVersion: tekton.dev/v1
      workspaces:
        - name: source
          workspace: source

    - name: shipwright
      runAfter: [sanity]
      taskRef:
        name: shipwright-trigger
        kind: Task
        apiVersion: tekton.dev/v1
      params:
        - name: BUILD_NAME
          value: $(params.build-name)
        - name: NAMESPACE
          value: $(params.namespace)

    - name: deploy
      runAfter: [shipwright]
      taskRef:
        name: deploy
        kind: Task
        apiVersion: tekton.dev/v1
      params:
        - name: manifest-path
          value: k8s/deployment.yaml
        - name: namespace
          value: $(params.namespace)
      workspaces:
        - name: source
          workspace: source
