apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-webapp-pipeline
spec:
  params:
    - name: git-url
      type: string
      description: Git repo URL (public)
    - name: git-revision
      type: string
      description: Branch, tag, or commit to checkout
      default: "main"
    - name: build-name
      type: string
      description: Shipwright Build name
      default: "java-webapp-build"
    - name: namespace
      type: string
      description: Target OpenShift project for deployment
  workspaces:
    - name: source
      description: Workspace for source checkout & artifacts

  tasks:
    - name: clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
      workspaces:
        - name: source
          workspace: source

    - name: build
      runAfter: [clone]
      taskRef:
        name: maven-build
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: sanity
      runAfter: [build]
      taskRef:
        name: war-sanity-check
        kind: ClusterTask
      workspaces:
        - name: source
          workspace: source

    - name: shipwright
      runAfter: [sanity]
      taskRef:
        name: shipwright-trigger
        kind: Task
      params:
        - name: BUILD_NAME    # exactly matches Task.spec.params
          value: $(params.build-name)
        - name: NAMESPACE     # exactly matches Task.spec.params
          value: $(params.namespace)

    - name: deploy
      runAfter: [shipwright]
      taskRef:
        name: deploy
        kind: Task
      params:
        - name: manifest-path
          value: k8s/deployment.yaml
        - name: namespace
          value: $(params.namespace)
      workspaces:
        - name: source
          workspace: source
