apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-webapp
  namespace: {{NAMESPACE}}
  labels:
    app: java-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-webapp
  template:
    metadata:
      labels:
        app: java-webapp
    spec:
      containers:
        - name: java-webapp
          # student’s namespace/project will be set at apply time
          image: image-registry.openshift-image-registry.svc:5000/{{NAMESPACE}}/java-webapp:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
