# File: pipeline-app-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-deploy-binding
  namespace: {{NAMESPACE}}
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{NAMESPACE}}
roleRef:
  kind: Role
  name: pipeline-deploy-permissions
  apiGroup: rbac.authorization.k8s.io
