apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-clone
  labels:
    tekton.dev/task: "git-clone"
spec:
  params:
    - name: url
      type: string
      description: Git repository URL to clone
    - name: revision
      type: string
      description: Git revision (branch, tag, commit)
      default: "main"
    - name: deleteExisting
      type: string
      description: Delete any existing contents?
      default: "true"
  workspaces:
    - name: source
      description: Where to clone the repo
  steps:
    - name: clone
      image: alpine/git
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      script: |
        #!/bin/sh
        set -e

        if [ "$(params.deleteExisting)" = "true" ]; then
          echo "🧹 Cleaning out $(workspaces.source.path)"
          # Remove everything, including hidden dirs/files
          rm -rf $(workspaces.source.path)/* $(workspaces.source.path)/.[!.]* || true
        fi

        echo "🔁 Cloning $(params.url) (rev=$(params.revision)) into $(workspaces.source.path)"
        git clone --single-branch --branch "$(params.revision)" "$(params.url)" "$(workspaces.source.path)"
        echo "✅ Clone complete, contents:"
        ls -la "$(workspaces.source.path)"
