apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
      description: Git repo URL
    - name: revision
      type: string
      description: branch/tag/commit
      default: "main"
    - name: deleteExisting
      type: string
      default: "true"
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        if [ "$(params.deleteExisting)" = "true" ]; then
          rm -rf "$(workspaces.source.path)"/*
        fi
        cd "$(workspaces.source.path)"
        git init .
        git remote add origin "$(params.url)"
        git fetch --depth=1 origin "$(params.revision)"
        git checkout FETCH_HEAD
        echo "✅ cloned $(params.url) @ $(params.revision)"
        ls -la "$(workspaces.source.path)"
