apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: git-clone
spec:
  params:
    - name: url
      type: string
    - name: revision
      type: string
    - name: deleteExisting
      type: string
      default: "true"
    - name: subdirectory
      type: string
      default: "repo"
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        set -e
        TARGET_DIR=$(workspaces.source.path)/$(params.subdirectory)

        echo "🧹 Cleaning target dir: $TARGET_DIR"
        rm -rf "$TARGET_DIR"
        mkdir -p "$TARGET_DIR"
        cd "$TARGET_DIR"

        echo "🔁 Cloning repo $(params.url) on branch $(params.revision) into $TARGET_DIR/"
        git clone --branch $(params.revision) --single-branch $(params.url) .
        echo "📂 Contents of $TARGET_DIR:"
        ls -la
