apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: war-sanity-check
spec:
  workspaces:
    - name: source
      description: The workspace containing build artifacts
  steps:
    - name: check-war
      image: registry.access.redhat.com/ubi8/ubi
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      script: |
        #!/bin/sh
        set -e
        echo "🕵️  Checking for generated WAR in target/"
        if [ ! -f /workspace/source/target/java-webapp.war ]; then
          echo "❌ java-webapp.war NOT FOUND in target/!"
          exit 1
        fi
        echo "✅ java-webapp.war exists"
